name: FPGA CI

on: [push, pull_request]

permissions:
  contents: read
  packages: write # Grant write permissions for publishing packages

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/${{ vars.IMAGE_NAME }}:latest ./docker/fpga-dev-env

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/${{ vars.IMAGE_NAME }}:latest

  build-and-simulate:
    needs: build-and-publish-docker-image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/${{ vars.IMAGE_NAME }}:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Verilog design
      run: make -C src/verilog/hello_world build

    - name: Simulate Verilog design
      run: make -C src/verilog/hello_world simulate

    - name: Verify simulation output
      run: |
        ls -l src/verilog/hello_world/hello_world.vvp
        ls -l src/verilog/hello_world/hello_world.vcd
