name: FPGA CI

on:
  push:
    branches:
      - main # Or your main development branch. Triggers on any push to main.
  pull_request:
    # Triggers on any pull request.
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force a complete rebuild of the Docker image, ignoring cache.'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write # Grant write permissions for publishing packages

jobs:
  build-and-publish-fpga-base-ci-image:
    uses: ./.github/workflows/build-and-publish-docker-image-template.yaml
    with:
      dockerfile_context_path: .
      dockerfile_path: docker/fpga-base-ci-env/Dockerfile
      image_name_var: fpga-base-ci-image
      force_rebuild: false

  verilog-hello-world:
    needs: build-and-publish-fpga-base-ci-image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/fpga-base-ci-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Verilog design
        run: mise run test -C src/verilog/hello_world

      - name: Upload simulation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verilog-simulation-artifacts
          path: |
            src/verilog/hello_world/*.vcd
            src/verilog/hello_world/*.vvp

  systemverilog-hello-world:
    needs: build-and-publish-fpga-base-ci-image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/fpga-base-ci-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test SystemVerilog design
        run: mise run test -C src/systemverilog/hello_world

      - name: Upload SystemVerilog simulation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: systemverilog-simulation-artifacts
          path: |
            src/systemverilog/hello_world/obj_dir/

  vhdl-hello-world:
    needs: build-and-publish-fpga-base-ci-image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/fpga-base-ci-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test VHDL design
        run: mise run test -C src/vhdl/hello_world

      - name: Verify VHDL executable exists
        run: |
          test -f src/vhdl/hello_world/hello_world || { echo "Error: hello_world executable not found for artifact upload!"; exit 1; }

      - name: Upload VHDL simulation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vhdl-simulation-artifacts
          path: |
            src/vhdl/hello_world/hello_world